name: Rust CI

on:
  workflow_call:
    inputs:
      rust-version:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: rustfmt
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: Format
        run: cargo fmt --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: cargo check
        run: cargo check

  fix:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: cargo fix
        run: |
          cargo fix
          git diff --exit-code
      - name: cargo fix edition
        run: |
          cargo fix --edition
          git diff --exit-code

  clippy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
          components: clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: cargo clippy
        run: cargo clippy

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Build
        run: cargo build

  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Run tests
        run: cargo test

  bench:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Rust ${{ inputs.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust-version }}
      - name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          prefix-key: ${{ inputs.rust-version }}
      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Run benchs
        run: cargo bench
